# Global Allowlist Rules

[allowlist]
  description = "Global Allowlist"
  regexes = [
    # Mimic the behavior of newer gitleaks versions
    # https://github.com/zricethezav/gitleaks/blob/96eed6aa0f507fe0c21bb46bec32637dc4cb1a9f/detect/detect.go#L226
    '''gitleaks:allow''',
  ]
  paths = [
    '''Godeps''',
    '''gems\/''',
    '''node_modules''',
    '''vendor''',
    # Quickstarts are FP heavy
    '''quickstart''',
    # Handle a lot of the github/docs cases
    '''lib\/rest\/static\/.+\/((.+)?github.+\.json|ghes.+\.json)''',
    # Ignore checked-in python packages
    '''lib/python[^/]+/site-packages''',
  ]
  files = [
    '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip|css)$''',
    '''(go.mod|go.sum)$''',
    '''^\.?gitleaks.toml$''',
    '''^\.?secrets.baseline$''',
  ]
